In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Simple_Linear_Reg.csv")
df

        Id  Price  Age_06_15
0        1  13500         57
1        2  13750         57
2        3  13950         58
3        4  14950         60
4        5  13750         64
5        6  12950         66
6        7  16900         61
7        8  18600         64
8        9  21500         61
9       10  12950         57
10      11  20950         59
11      12  19950         56
12      13  19600         59
13      14  21500         65
14      15  22500         66
15      16  22000         62
16      17  22750         64
17      18  17950         58
18      19  16750         58
19      20  16950         64
20      21  15950         64
21      22  16950         63
22      23  15950         62
23      24  16950         62
24      25  16250         63
25      26  15950         59
26      27  17495         61
27      28  15750         63
28      29  16950         62
29      30  17950         64
...    ...    ...        ...
1406  1413   8950        104
1407  1414   8250        103
1408  1415   9250        114
1409  1416   7900        109
1410  1417   8500        112
1411  1418   7950        110
1412  1419   9950        103
1413  1420   8750        108
1414  1421   7500        114
1415  1422   6950        106
1416  1423   8950        113
1417  1424   8750        113
1418  1425   7750        107
1419  1426   8450        109
1420  1427   8150        110
1421  1428   8500        112
1422  1429   7600        112
1423  1430   7950        114
1424  1431   7750        107
1425  1432   7950        114
1426  1433   9950        112
1427  1434   8950        105
1428  1435   8450        106
1429  1436   8950        112
1430  1437   8450        114
1431  1438   7500        103
1432  1439  10845        106
1433  1440   8500        105
1434  1441   7250        104
1435  1442   6950        110

[1436 rows x 3 columns]

In [3]:
np.log(df)

            Id      Price  Age_06_15
0     0.000000   9.510445   4.043051
1     0.693147   9.528794   4.043051
2     1.098612   9.543235   4.060443
3     1.386294   9.612467   4.094345
4     1.609438   9.528794   4.158883
5     1.791759   9.468851   4.189655
6     1.945910   9.735069   4.110874
7     2.079442   9.830917   4.158883
8     2.197225   9.975808   4.110874
9     2.302585   9.468851   4.043051
10    2.397895   9.949894   4.077537
11    2.484907   9.900984   4.025352
12    2.564949   9.883285   4.077537
13    2.639057   9.975808   4.174387
14    2.708050  10.021271   4.189655
15    2.772589   9.998798   4.127134
16    2.833213  10.032320   4.158883
17    2.890372   9.795345   4.060443
18    2.944439   9.726154   4.060443
19    2.995732   9.738023   4.158883
20    3.044522   9.677214   4.158883
21    3.091042   9.738023   4.143135
22    3.135494   9.677214   4.127134
23    3.178054   9.738023   4.127134
24    3.218876   9.695848   4.143135
25    3.258097   9.677214   4.077537
26    3.295837   9.769670   4.110874
27    3.332205   9.664596   4.143135
28    3.367296   9.738023   4.127134
29    3.401197   9.795345   4.158883
...        ...        ...        ...
1406  7.253470   9.099409   4.644391
1407  7.254178   9.017968   4.634729
1408  7.254885   9.132379   4.736198
1409  7.255591   8.974618   4.691348
1410  7.256297   9.047821   4.718499
1411  7.257003   8.980927   4.700480
1412  7.257708   9.205328   4.634729
1413  7.258412   9.076809   4.682131
1414  7.259116   8.922658   4.736198
1415  7.259820   8.846497   4.663439
1416  7.260523   9.099409   4.727388
1417  7.261225   9.076809   4.727388
1418  7.261927   8.955448   4.672829
1419  7.262629   9.041922   4.691348
1420  7.263330   9.005773   4.700480
1421  7.264030   9.047821   4.718499
1422  7.264730   8.935904   4.718499
1423  7.265430   8.980927   4.736198
1424  7.266129   8.955448   4.672829
1425  7.266827   8.980927   4.736198
1426  7.267525   9.205328   4.718499
1427  7.268223   9.099409   4.653960
1428  7.268920   9.041922   4.663439
1429  7.269617   9.099409   4.718499
1430  7.270313   9.041922   4.736198
1431  7.271009   8.922658   4.634729
1432  7.271704   9.291459   4.663439
1433  7.272398   9.047821   4.653960
1434  7.273093   8.888757   4.644391
1435  7.273786   8.846497   4.700480

[1436 rows x 3 columns]

In [4]:
from sklearn.preprocessing import MinMaxScaler

In [6]:
range_fn = MinMaxScaler()
range_data = pd.DataFrame(range_fn.fit_transform(df))
range_data

             0         1         2
0     0.000000  0.325044  0.278481
1     0.000694  0.333925  0.278481
2     0.001388  0.341030  0.291139
3     0.002082  0.376554  0.316456
4     0.002776  0.333925  0.367089
5     0.003470  0.305506  0.392405
6     0.004164  0.445826  0.329114
7     0.004858  0.506217  0.367089
8     0.005552  0.609236  0.329114
9     0.006246  0.305506  0.278481
10    0.006940  0.589698  0.303797
11    0.007634  0.554174  0.265823
12    0.008328  0.541741  0.303797
13    0.009022  0.609236  0.379747
14    0.009715  0.644760  0.392405
15    0.010409  0.626998  0.341772
16    0.011103  0.653641  0.367089
17    0.011797  0.483126  0.291139
18    0.012491  0.440497  0.291139
19    0.013185  0.447602  0.367089
20    0.013879  0.412078  0.367089
21    0.014573  0.447602  0.354430
22    0.015267  0.412078  0.341772
23    0.015961  0.447602  0.341772
24    0.016655  0.422735  0.354430
25    0.017349  0.412078  0.303797
26    0.018043  0.466963  0.329114
27    0.018737  0.404973  0.354430
28    0.019431  0.447602  0.341772
29    0.020125  0.483126  0.367089
...        ...       ...       ...
1406  0.979875  0.163410  0.873418
1407  0.980569  0.138544  0.860759
1408  0.981263  0.174067  1.000000
1409  0.981957  0.126110  0.936709
1410  0.982651  0.147425  0.974684
1411  0.983345  0.127886  0.949367
1412  0.984039  0.198934  0.860759
1413  0.984733  0.156306  0.924051
1414  0.985427  0.111901  1.000000
1415  0.986121  0.092362  0.898734
1416  0.986815  0.163410  0.987342
1417  0.987509  0.156306  0.987342
1418  0.988203  0.120782  0.911392
1419  0.988897  0.145648  0.936709
1420  0.989591  0.134991  0.949367
1421  0.990285  0.147425  0.974684
1422  0.990978  0.115453  0.974684
1423  0.991672  0.127886  1.000000
1424  0.992366  0.120782  0.911392
1425  0.993060  0.127886  1.000000
1426  0.993754  0.198934  0.974684
1427  0.994448  0.163410  0.886076
1428  0.995142  0.145648  0.898734
1429  0.995836  0.163410  0.974684
1430  0.996530  0.145648  1.000000
1431  0.997224  0.111901  0.860759
1432  0.997918  0.230728  0.898734
1433  0.998612  0.147425  0.886076
1434  0.999306  0.103020  0.873418
1435  1.000000  0.092362  0.949367

[1436 rows x 3 columns]

In [8]:
min(df["Price"])

4350

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:

range_fn1=StandardScaler()
range_data1=pd.DataFrame(range_fn1.fit_transform(df))
range_data1

             0         1         2
0    -1.730723  0.763763 -1.771966
1    -1.728321  0.832715 -1.771966
2    -1.725919  0.887877 -1.718184
3    -1.723517  1.163685 -1.610620
4    -1.721115  0.832715 -1.395491
5    -1.718713  0.612068 -1.287926
6    -1.716311  1.701512 -1.556838
7    -1.713909  2.170387 -1.395491
8    -1.711507  2.970232 -1.556838
9    -1.709105  0.612068 -1.771966
10   -1.706703  2.818537 -1.664402
11   -1.704302  2.542729 -1.825749
12   -1.701900  2.446196 -1.664402
13   -1.699498  2.970232 -1.341709
14   -1.697096  3.246041 -1.287926
15   -1.694694  3.108137 -1.503055
16   -1.692292  3.314993 -1.395491
17   -1.689890  1.991111 -1.718184
18   -1.687488  1.660141 -1.718184
19   -1.685086  1.715303 -1.395491
20   -1.682684  1.439494 -1.395491
21   -1.680282  1.715303 -1.449273
22   -1.677880  1.439494 -1.503055
23   -1.675478  1.715303 -1.503055
24   -1.673076  1.522237 -1.449273
25   -1.670675  1.439494 -1.664402
26   -1.668273  1.865618 -1.556838
27   -1.665871  1.384332 -1.449273
28   -1.663469  1.715303 -1.503055
29   -1.661067  1.991111 -1.395491
...        ...       ...       ...
1406  1.660803 -0.491167  0.755797
1407  1.663204 -0.684233  0.702015
1408  1.665606 -0.408424  1.293619
1409  1.668008 -0.780766  1.024708
1410  1.670410 -0.615281  1.186055
1411  1.672812 -0.766976  1.078490
1412  1.675214 -0.215358  0.702015
1413  1.677616 -0.546329  0.970926
1414  1.680018 -0.891089  1.293619
1415  1.682420 -1.042784  0.863362
1416  1.684822 -0.491167  1.239837
1417  1.687224 -0.546329  1.239837
1418  1.689626 -0.822137  0.917144
1419  1.692028 -0.629071  1.024708
1420  1.694430 -0.711814  1.078490
1421  1.696831 -0.615281  1.186055
1422  1.699233 -0.863509  1.186055
1423  1.701635 -0.766976  1.293619
1424  1.704037 -0.822137  0.917144
1425  1.706439 -0.766976  1.293619
1426  1.708841 -0.215358  1.186055
1427  1.711243 -0.491167  0.809579
1428  1.713645 -0.629071  0.863362
1429  1.716047 -0.491167  1.186055
1430  1.718449 -0.629071  1.293619
1431  1.720851 -0.891089  0.702015
1432  1.723253  0.031491  0.863362
1433  1.725655 -0.615281  0.809579
1434  1.728057 -0.960042  0.755797
1435  1.730458 -1.042784  1.078490

[1436 rows x 3 columns]

In [11]:
import statistics
statistics.stdev(df["Price"])

3626.9645849102444

In [12]:
np.mean(df["Price"])

10730.824512534818